### PR TITLE
preinstall is missed when running make pkg

### PR DESCRIPTION
**Pull request by timhberry**

### CODE REVIEW

**Comment by timhberry** [comment]
I signed it!

**Comment by timhberry** [comment]
The failed checks don't appear to be related to my commit:

No local packages or download links found for simian-M2Crypto==0.22.3
error: Could not find suitable distribution for Requirement.parse('simian-M2Crypto==0.22.3')
make: *** [test] Error 1

**Comment by maximermilov** [comment]
preinstall fail during package installation with this patch.

> The failed checks don't appear to be related to my commit:

Yes, travis-ci switched to use homebrew's python by default. Which break tests.

**Comment by maximermilov** [comment]
fixed in badd495cd57f3074b6680b23c71521f814ec122d

**Pull request closed without merging**
